#!/usr/bin/env bash

# general
alias l='ls -lahG'
alias dotfiles="atom $HOME/dotfiles"
alias psimple="python -m SimpleHTTPServer"
alias hru="heroku"
alias cddash="cd ~/Projects/dashboard"
alias dash="cddash && atom ."
alias routines="cddash && atom routines.md"
alias atomconf="atom ~/.atom"

# mercurial
alias hc='hg commit'
alias ha='hg amend'
alias hu='hg update'
alias ad='arc diff'

# arc
alias adr='arc diff --reviewers'
alias adm='arc diff -m'

# git
alias g='git status'
alias gst='git status'
alias gf='git fetch'
alias gm='git merge'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gck='git checkout'
alias gd='git diff'
alias gca='git commit -a'
alias gcaa='git commit -a --amend -C HEAD'
alias gg='git grep'
alias glo='git log'
alias gl='git pull'
alias gp='git push'
alias lg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%ad>%Creset' --abbrev-commit --date=short"
function gpm() {
  ga -A && gc -m $1 && gp
}
alias ghu="git push heroku master"
